staging: sep: fix driver build and kconfig
Fix build errors in staging/sep/ by making DX_SEP depend on
CRYPTO.

drivers/built-in.o: In function `sep_sha1_init':
sep_crypto.c:(.text+0x245ece): undefined reference to `crypto_enqueue_request'
drivers/built-in.o: In function `sep_sha1_update':
sep_crypto.c:(.text+0x245f4f): undefined reference to `crypto_enqueue_request'
drivers/built-in.o: In function `sep_sha1_final':
sep_crypto.c:(.text+0x245fcf): undefined reference to `crypto_enqueue_request'
drivers/built-in.o: In function `sep_sha1_finup':
sep_crypto.c:(.text+0x24604f): undefined reference to `crypto_enqueue_request'
drivers/built-in.o: In function `sep_sha1_digest':
sep_crypto.c:(.text+0x2460de): undefined reference to `crypto_enqueue_request'
drivers/built-in.o:sep_crypto.c:(.text+0x24616e): more undefined references to `crypto_enqueue_request' follow
drivers/built-in.o: In function `sep_crypto_block':
sep_crypto.c:(.text+0x247c81): undefined reference to `ablkcipher_walk_phys'
sep_crypto.c:(.text+0x247e40): undefined reference to `ablkcipher_walk_phys'
drivers/built-in.o: In function `sep_dequeuer':
sep_crypto.c:(.text+0x248ab9): undefined reference to `crypto_dequeue_request'
sep_crypto.c:(.text+0x248afa): undefined reference to `crypto_ahash_type'
sep_crypto.c:(.text+0x248fdf): undefined reference to `crypto_dequeue_request'
drivers/built-in.o: In function `sep_crypto_setup':
(.text+0x24902a): undefined reference to `crypto_init_queue'
drivers/built-in.o: In function `sep_crypto_setup':
(.text+0x24909c): undefined reference to `crypto_register_ahash'
drivers/built-in.o: In function `sep_crypto_setup':
(.text+0x2490c4): undefined reference to `crypto_register_alg'
drivers/built-in.o: In function `sep_crypto_setup':
(.text+0x2490f7): undefined reference to `crypto_unregister_alg'
drivers/built-in.o: In function `sep_crypto_setup':
(.text+0x249118): undefined reference to `crypto_unregister_ahash'
drivers/built-in.o: In function `sep_crypto_takedown':
(.text+0x249176): undefined reference to `crypto_unregister_ahash'
drivers/built-in.o: In function `sep_crypto_takedown':
(.text+0x249197): undefined reference to `crypto_unregister_alg'

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>