olpc_battery: Fix build failure caused by sysfs changes
drivers/power/olpc_battery.c:387: error: unknown field 'owner' specified in initializer
drivers/power/olpc_battery.c:387: warning: excess elements in struct initializer
drivers/power/olpc_battery.c:387: warning: (near initialization for 'olpc_bat_eeprom.attr')

The .owner field has been dropped from the attr struct.

Signed-off-by: David Woodhouse <David.Woodhouse@intel.com>