ARM: highbank: add ifdef guards to core.h
Fixes build error due to multiple includes:

In file included from arch/arm/mach-highbank/sysregs.h:23:0,
from arch/arm/mach-highbank/system.c:20:
arch/arm/mach-highbank/core.h:8:91: error: redefinition of 'highbank_lluart_map_io'
In file included from arch/arm/mach-highbank/system.c:19:0:
arch/arm/mach-highbank/core.h:8:91: note: previous definition of 'highbank_lluart_map_io' was here

Signed-off-by: Olof Johansson <olof@lixom.net>