ARM: davinci: fix build break due to missing include
arch/arm/mach-davinci/board-da850-evm.c: In function 'da850_evm_init':
arch/arm/mach-davinci/board-da850-evm.c:1516:2: error: implicit declaration of function 'sram_get_gen_pool' [-Werror=implicit-function-declaration]
arch/arm/mach-davinci/board-da850-evm.c:1516:31: warning: assignment makes pointer from integer without a cast [enabled by default]

Signed-off-by: Olof Johansson <olof@lixom.net>
Cc: Sekhar Nori <nsekhar@ti.com>
Cc: Kevin Hilman <khilman@ti.com>