MIPS: powertv: Drop SYS_HAS_EARLY_PRINTK
PowerTV does not provide a prom_putchar function needed for early
printk so remove this symbol for this platform.

Fixes the following problem when EARLY_PRINTK is enabled for powertv:

arch/mips/kernel/early_printk.c:24: undefined reference to `prom_putchar'
arch/mips/kernel/early_printk.c:23: undefined reference to `prom_putchar'

Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>
Acked-by: Steven J. Hill <Steven.Hill@imgtec.com>
Cc: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/5477/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>