x86, olpc: Fix dependency on POWER_SUPPLY
As reported by Randy Dunlap, CONFIG_POWER_SUPPLY=m caused a
compile error:

  arch/x86/built-in.o: In function `battery_status_changed':
   olpc-xo15-sci.c:(.text+0x3acdd): undefined reference to `power_supply_get_by_name'
   olpc-xo15-sci.c:(.text+0x3ad04): undefined reference to `power_supply_changed'

The SCI drivers, as bool, require POWER_SUPPLY to be builtin.
Use select to make that a hard requirement and avoid this build
failure.

Reported-by: Randy Dunlap <rdunlap@xenotime.net>
Acked-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Daniel Drake <dsd@laptop.org>
Signed-off-by: Ingo Molnar <mingo@elte.hu>