ARM: nomadik: fix OF compilation regression
The Nomadik Device Tree patch series accidentally
selected OF instead of USE_OF which led to problems
during compile:

arch/arm/kernel/devtree.c: In function 'arm_dt_memblock_reserve':
/home/elinwal/linux-arm-soc/arch/arm/kernel/devtree.c:43:7: error: 'initial_boot_params' undeclared (first use in this function)
(etc).

This fixes it up by selecting USE_OF instead.

Reported-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
Signed-off-by: Olof Johansson <olof@lixom.net>