Staging: lustre: Fix space required after ','
This patch fixes the following checkpatch.pl warning in lustre/ldlm/interval_tree.c-
ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Rashika Kheria <rashika.kheria@gmail.com>
Reviewed-by: Peter P Waskiewicz Jr <peter.p.waskiewicz.jr@intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>