TTY: mn10300-serial, fix build breakage
By the recent `switch flipping' patches we introduced a build failure
in the driver:
mn10300-serial.c:527:19: error: 'port' redeclared as different kind of symbol

I did not notice because I did not even find a compiler for that new
architecture. Hopefully everything is all right now as I cannot test
it.

Signed-off-by: Jiri Slaby <jslaby@suse.cz>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>