ARM: fix build errors caused by selection of errata 798181
Several configurations are selecting errata 798181 without SMP
being selected.  This causes a warning from Kconfig:

warning: (ARCH_HIGHBANK && ARCH_KEYSTONE && SOC_OMAP5 && ARCH_TEGRA_114_SOC) selects ARM_ERRATA_798181 which has unmet direct dependencies (CPU_V7 && SMP)

The dependencies are compile time dependencies; select violates these,
resulting in:

arch/arm/kernel/built-in.o: In function `setup_processor':
psci.c:(.init.text+0x808): undefined reference to `erratum_a15_798181_init'

at build time.  Fix this by fixing the select statements for Tegra and
Highbank.

Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>