keucr: fixes space required before open parenthesis error
This patch fixes the following checkpatch error,
ERROR: space required before the open parenthesis '('

Signed-off-by: Amarjargal Gundjalam <amarjargal16@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>