ARM: fix missing bug.h include in arch/arm/kernel/insn.c
arch/arm/kernel/insn.c: In function '__arm_gen_branch_thumb2':
arch/arm/kernel/insn.c:13: error: implicit declaration of function 'WARN_ON_ONCE'

Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>