Staging: quickstart: depends on INPUT
quickstart uses input_*() functions so it should depend on INPUT.

ERROR: "input_register_device" [drivers/staging/quickstart/quickstart.ko] undefined!
ERROR: "input_allocate_device" [drivers/staging/quickstart/quickstart.ko] undefined!
ERROR: "input_event" [drivers/staging/quickstart/quickstart.ko] undefined!
ERROR: "input_free_device" [drivers/staging/quickstart/quickstart.ko] undefined!
ERROR: "input_unregister_device" [drivers/staging/quickstart/quickstart.ko] undefined!

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Angelo Arrifano <miknix@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>