leds: leds-sunfire: use dev_err()/pr_err() instead of printk()
Fixed the checkpatch errors and warnings as below:

  ERROR: spaces required around that '=' (ctx:VxW)
  WARNING: Prefer netdev_err(netdev, ... then dev_err(dev, ... then pr_err(...  to printk(KERN_ERR ...

Signed-off-by: Jingoo Han <jg1.han@samsung.com>
Signed-off-by: Bryan Wu <cooloney@gmail.com>