clockevents: Add missing tick_check_broadcast_expired() for CLOCKEVENTS=n
Fengs build robot reports:

arch/arm/kernel/process.c: In function 'cpu_idle':
arch/arm/kernel/process.c:211:4: error: implicit declaration of function
'tick_check_broadcast_expired' [-Werror=implicit-function-declaration]

Add the missing inline function for non clockevent builds

Reported-by: Wu Fengguang <fengguang.wu@intel.com>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>