Staging: pohmelfs: fix spaces and TAB coding style issue in net.c
This is a patch to the net.c file that fixed up a TAB and spaces Errors found by the checkpatch.pl tools, like

ERROR: switch and case should be at the same indent
and
spaces required around that '=' (ctx:VxV)

Signed-off-by: Ruslan Pisarev <ruslan@rpisarev.org.ua>
Acked-by: Evgeniy Polyakov <zbr@ioremap.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>