staging/hv: add missing include causing build error
This fixes following build error:

In file included from drivers/staging/hv/channel.h:28,
                 from drivers/staging/hv/vmbus_private.h:30,
                 from drivers/staging/hv/hv.c:28:
drivers/staging/hv/channel_mgmt.h:234: error: field ‘work’ has incomplete type

Signed-off-by: Mariusz Kozlowski <mk@lab.zgora.pl>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>