ASoC: Intel: Fix build with CONFIG_SLEEP enabled.
Fix the following build error when CONFIG_SLEEP is enabled and CONFIG_RUNTIME
is disabled. The BDW ADSP sleep PM functionality depends on the runtime pm
calls for context save/restore.

All error/warnings:

>> ERROR: "snd_soc_suspend" undefined!
>> ERROR: "snd_soc_resume" undefined!

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>