mfd: vexpress: Export global functions to fix build error
Compiling vexpress client drivers as module results in error messages such as

ERROR: "__vexpress_config_func_get" [drivers/hwmon/vexpress.ko] undefined!
ERROR: "vexpress_config_func_put" [drivers/hwmon/vexpress.ko] undefined!

This is because the global functions in drivers/mfd/vexpress-config.c are not
exported. Fix it.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>