Staging: lustre: Fix paranthesis not required around return
This patch fixes the following checkpatch.pl warning in lustre/ldlm/ldlm_extent.c-
ERROR: return is not a function, parentheses are not required

Signed-off-by: Rashika Kheria <rashika.kheria@gmail.com>
Reviewed-by: Peter P Waskiewicz Jr <peter.p.waskiewicz.jr@intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>