m68k: amiga: Add linux/irq.h to make it compile again
The removal of linux/irq.h from kernel_stat.h causes 

 arch/m68k/amiga/cia.c:171: error: 'handle_simple_irq' undeclared

Reported-by: Ingo Molnar <mingo@kernel.org>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>