cris: Switch cris to drivers/Kconfig
allmodconfig:

drivers/video/console/fonts.c:71:2: error: #error No fonts configured.

This is caused by cris not using the generic drivers/Kconfig, and thus not
traversing drivers/video/console/Kconfig.
As the build system does traverse drivers/video/console/Makefile, fonts.c
was compiled with an inconsistent configuration.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>