staging: imx-drm: add missing MFD_SYSCON dependency for LDB
Added missing MFD_SYSCON dependency for LVDS display bridge
in order to fix the following link error.

drivers/staging/imx-drm/imx-ldb.c:484: undefined reference to `syscon_regmap_lookup_by_phandle'

Signed-off-by: Jingoo Han <jg1.han@samsung.com>
Acked-by: Philipp Zabel <p.zabel@pengutronix.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>