staging: fix ccg build when NET is not enabled
Fix build errors in ccg when CONFIG_NET is not enabled
by adding "depends on NET":

ERROR: "netif_carrier_on" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "netif_carrier_off" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "skb_realloc_headroom" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "skb_trim" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "netif_rx" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "ethtool_op_get_link" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "free_netdev" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "register_netdev" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "skb_push" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "skb_pull" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "dev_kfree_skb_any" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "skb_queue_tail" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "__alloc_skb" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "eth_type_trans" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "eth_validate_addr" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "skb_dequeue" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "unregister_netdev" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "__netif_schedule" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "skb_put" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "eth_mac_addr" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "dev_get_stats" [drivers/staging/ccg/g_ccg.ko] undefined!
ERROR: "alloc_etherdev_mqs" [drivers/staging/ccg/g_ccg.ko] undefined!

Signed-off-by: Randy Dunlap <rdunlap@xenotime.net>
Cc: Andrzej Pietrasiewicz <andrzej.p@samsung.com>
Cc: Mike Lockwood <lockwood@android.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>