staging: rtl8187se: Fix braces in ieee80211/ieee80211_crypt_tkip.c
This patch fixes braces errors as the codingStyle of the kernel
recommends.

Thus, this patch fixes these errors and warning messages found by
checkpatch.pl:
WARNING: braces {} are not necessary for single statement blocks
ERROR: that open brace { should be on the previous line

Signed-off-by: Ana Rey <anarey@gmail.com>
Reviewed-by: Bob Copeland <me@bobcopeland.com>
Signed-off-by: Peter P Waskiewicz Jr <peter.p.waskiewicz.jr@intel.com>