drivers:staging:silicom fixed checkpatch coding style error on macros
checkpatch displays below errors for bypasslib/bp_ioctl.h file

	 ERROR: Macros with complex values should be enclosed in parenthesis
Hence added parenthesis for macros with complex values.

Signed-off-by: Surendra Patil <surendra.tux@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>