staging: ft1000: ft1000-pcmcia: Add require space after that ','
This patch fixes checkpatch.pl error in file ft1000_hw.c
ERROR: space required after that ';' (ctx:VxV)

Signed-off-by: Aybuke Ozdemir <aybuke.147@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>