input: Export matrix_keypad_parse_of_params()
Couple of input drivers depend on this symbol:

ERROR: "matrix_keypad_parse_of_params" [drivers/input/keyboard/tca8418_keypad.ko] undefined!
ERROR: "matrix_keypad_parse_of_params" [drivers/input/keyboard/cros_ec_keyb.ko] undefined!

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Acked-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
Acked-by: Randy Dunlap <rdunlap@infradead.org>
Acked-by: Simon Glass <sjg@chromium.org>
Signed-off-by: Michal Marek <mmarek@suse.cz>
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>