ARM: imx: Fix build error due to missing irqs.h include
commit bc8966 (ARM: fiq: change FIQ_START to a variable) introduced the
following build error for imx_v4_v5_defconfig:

arch/arm/plat-mxc/avic.c:220:11: error: 'FIQ_START' undeclared (first use in this function)

Include the missing header file to fix it.

Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>