c2port: fix build error for duramar2150 due to missing header.
This file needs the basic headers for resource management,
otherwise we will see this build error:

 CC [M]  drivers/misc/c2port/c2port-duramar2150.o
 drivers/misc/c2port/c2port-duramar2150.c: In function ‘duramar2150_c2port_init’:
 drivers/misc/c2port/c2port-duramar2150.c:125:2: error: implicit declaration of function ‘request_region’ [-Werror=implicit-function-declaration]
 drivers/misc/c2port/c2port-duramar2150.c:139:2: error: implicit declaration of function ‘release_region’ [-Werror=implicit-function-declaration]

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>