keurc: fixes spaces required around error
This patch fixes the following checkpatch error,
ERROR: spaces required around that ' '

Signed-off-by: Amarjargal Gundjalam <amarjargal16@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>