video: clps711x: Fix driver build for CONFIG_FB=m
This patch fixes building CLPS711X FB driver if the framebuffer
core is used as a module.

LD      init/built-in.o
  drivers/built-in.o: In function `clps711x_fb_remove':
  :(.text+0x44a8): undefined reference to `unregister_framebuffer'
  drivers/built-in.o: In function `clps711x_fb_probe':
  :(.text+0x44cc): undefined reference to `fb_get_options'
  :(.text+0x45d8): undefined reference to `fb_alloc_cmap'
  :(.text+0x45e4): undefined reference to `register_framebuffer'
make: *** [vmlinux] Error 1

Reported-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Alexander Shiyan <shc_work@mail.ru>
Signed-off-by: Tomi Valkeinen <tomi.valkeinen@ti.com>