staging: vt6656: fixed the switch case indentation level error
aligned the case statements of 'switch' so that the switch and
case are on same indentation level to fix the following error.
	ERROR: switch and case should be at the same indent

Signed-off-by: Nandini Hanumanthagowda <nandu.hgowda@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>