[SCSI] libosd: remover duplicate __bitwise annotation
__be32 is already a __bitwise type so we don't need the second __bitwise
here.  It causes a Sparse error:
include/scsi/osd_protocol.h:110:26: error: invalid modifier

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Acked-by: Benny Halevy <bhalevy@tonian.com>
Signed-off-by: James Bottomley <JBottomley@Parallels.com>