Staging: vt6655: Add require space before that '('
This patch fixes checkpatch.pl error in file device_main.c
ERROR: space required before the open parenthesis '('

Signed-off-by: Aybuke Ozdemir <aybuke.147@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>