Staging:unisys: Add Kconfig dependency on UNISYS_VISORUTIL to UNISYS_CHANNELSTUB
The visorchannelstub module references the variable unisys_spar_platform
which is declared in the visorutil module.  Add the proper dependency to
Kconfig to ensure that visorutil is enabled when building visorchannelstub.

This address the build error:
   drivers/built-in.o: In function `channel_mod_init':
   chanstub.c:(.init.text+0xbe24): undefined reference to `unisys_spar_platform'

Reported by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Ken Cox <jkc@redhat.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>