ARM: mxc: Include missing irqs.h header
Include irqs.h in order to fix the following build error:

arch/arm/plat-mxc/tzic.c:195:11: error: 'FIQ_START' undeclared (first use in this function)

Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Acked-by: Dirk Behme <dirk.behme@de.bosch.com>
Signed-off-by: Olof Johansson <olof@lixom.net>