tty: bfin, define inlined structures
struct bfin_serial_port contains structs circ_buf, timer_list, and
work_struct directly (not pointers). This means that these structures
have to be defined completely to be inlined in struct
bfin_serial_port.

So instead of struct declarations, define the structures by including
proper headers. They were pulled in by linux/serial_core.h or others
until now. But experimenting with circ_buf removal from serial_core,
struct circ_buf becomes undefined in bfin_serial:

In file included from arch/blackfin/kernel/debug-mmrs.c:21:0:
arch/blackfin/include/asm/bfin_serial.h:44:18: error: field 'rx_dma_buf' has incomplete type

Signed-off-by: Jiri Slaby <jslaby@suse.cz>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>