staging: hv: make HYPERV_UTILS depend on NLS to prevent a build error
When HYPERV_UTILS=y and NLS=n the build fails with this error:
MODPOST 3 modules
ERROR: "utf8s_to_utf16s" [drivers/staging/hv/hv_utils.ko] undefined!
This patch fixes this by adding a dependency on NLS to HYPERV_UTILS.

Signed-off-by: Peter Foley <pefoley2@verizon.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>