Staging: rtl8187se: Remove unnecessary comments in ieee80211_crypt_ccmp.c
This patch removes unnecessary comments written in ieee80211/ieee80211_crypt_ccmp.c.
And hence also, removes the following checkpatch.pl issue-
ERROR: do not use C99 // comments

Signed-off-by: Rashika Kheria <rashika.kheria@gmail.com>
Reviewed-by: Josh Triplett <josh@joshtriplett.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>