ARM: exynos: fix building with CONFIG_OF disabled
irq_of_parse_and_map does not have an empty definition for the
!CONFIG_OF case, so we should not try to call it then:

arch/arm/mach-exynos/common.c: In function 'combiner_init':
arch/arm/mach-exynos/common.c:576:3: warning: implicit declaration of function 'irq_of_parse_and_map'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>