imx-drm: imx-hdmi: Remove parentheses from returns
Fix the following checkpatch warnings:

ERROR: return is not a function, parentheses are not required
#462: FILE: drivers/staging/imx-drm/imx-hdmi.c:462:
+       return (hdmi->hdmi_data.enc_in_format !=

ERROR: return is not a function, parentheses are not required
#468: FILE: drivers/staging/imx-drm/imx-hdmi.c:468:
+       return ((hdmi->hdmi_data.enc_out_format == YCBCR422_8BITS) &&

ERROR: return is not a function, parentheses are not required
#475: FILE: drivers/staging/imx-drm/imx-hdmi.c:475:
+       return ((hdmi->hdmi_data.enc_in_format == YCBCR422_8BITS) &&

While at it, broke the return code from is_color_space_decimation() and
is_color_space_interpolation() for better readability

Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Reviewed-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>