keucr: fixes space required after error
This patch fixes the following checkpatch error,
ERROR: space required after that ' '

Signed-off-by: Amarjargal Gundjalam <amarjargal16@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>