sparc: fix implicit use of uaccess.h header in mdesc.c
Building sparc64 with the module.h cleanup reveals this implicit
include being taken advantage of:

arch/sparc/kernel/mdesc.c: In function 'mdesc_read':
arch/sparc/kernel/mdesc.c:900: error: implicit declaration of function 'copy_to_user'

Fix it up before the implicit module.h presence is removed.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>