staging:iio:adc:Kconfig: Let MXS_LRADC depend on HAS_IOMEM
MXS_LRADC need HAS_IOMEM, so let it depend on HAS_IOMEM

The related error (with allmodconfig under score):

    MODPOST 1365 modules
  ERROR: "devm_ioremap_resource" [drivers/staging/iio/adc/mxs-lradc.ko] undefined!

Signed-off-by: Chen Gang <gang.chen.5i5j@gmail.com>
Acked-by: Marek Vasut <marex@denx.de>
Signed-off-by: Jonathan Cameron <jic23@kernel.org>