backlight: tosa: fix checkpatch error and warning
This patch fixes the checkpatch error and warning as below:

  ERROR: spaces required around that '?' (ctx:VxW)
  ERROR: space required after that ',' (ctx:VxV)

Also, unnecessary lines are removed.

Signed-off-by: Jingoo Han <jg1.han@samsung.com>
Cc: Richard Purdie <rpurdie@rpsys.net>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>