Staging rtl8192e: Fixing checkpatch errors
We fixed checkpatch errors of the following type:
	ERROR: "foo * bar" should be "foo *bar"

The error was fixed in the following files of the rtl8192e staging driver:
	rtllib_softmac.c
	rtllib_rx.c
	rtllib_crypt.c
	rtllib.h

There are no functional changes in this patch.

Signed-off-by: Matthias Schoepe <matthias.schoepe@studium.uni-erlangen.de>
Signed-off-by: Andreas Frembs <andreas.frembs@studium.uni-erlangen.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>