powerpc/40x: Use {upper,lower}_32_bits for msi_phys
Fix a build error when -Werror is set:
	arch/powerpc/sysdev/ppc4xx_msi.c: In function ‘ppc4xx_setup_pcieh_hw’:
	arch/powerpc/sysdev/ppc4xx_msi.c:178:2: error: right shift count >= width of type [-Werror]

Signed-off-by: Josh Boyer <jwboyer@gmail.com>