Makefile: Add missing soc_camera/ directory
drivers/built-in.o: In function `imx074_s_power':
imx074.c:(.text+0x1de93d0): undefined reference to `soc_camera_power_on'
imx074.c:(.text+0x1de93f3): undefined reference to `soc_camera_power_off'
drivers/built-in.o: In function `mt9m001_s_mbus_config':

Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>