ARM: ux500: fix missing include
Commit db298da2c31e1dcf7c9b7c9cef6217ad3449ebb7
"ARM: nomadik: move platform_data definition"
moved the Ux500-specific musb header from <mach/usb.h>
to <linux/platform_data/usb-musb-ux500.h>

However that makes some board code fail to compile
now:

CC      arch/arm/mach-ux500/board-mop500.o
linux/arch/arm/mach-ux500/cpu-db8500.c: In function 'u8500_init_devices':
linux/arch/arm/mach-ux500/cpu-db8500.c:226:2: error: implicit declaration of function 'ux500_add_usb' [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[3]: *** [arch/arm/mach-ux500/cpu-db8500.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [arch/arm/mach-ux500] Error 2
make[2]: *** Waiting for unfinished jobs....

So fix this up by adding the proper include file that
appears to have been brought in implicitly one or another
way in the past.

Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
Signed-off-by: Olof Johansson <olof@lixom.net>