staging: lustre: lustre: ptlrpc: Fix space required
This patch fixes the checkpatch.pl issue
Error: Required space after " '+' ',' '=' '(' ' if' "

Signed-off-by: Hema Prathaban <hemaklnce@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>