max8903_charger: Add GENERIC_HARDIRQS as a dependency (fixes S390 build)
S390 is special as it doesn't have IRQ lines, so these errors pop up:

drivers/built-in.o: In function 'max8903_remove':
drivers/power/max8903_charger.c:355: undefined reference to 'free_irq'
drivers/power/max8903_charger.c:357: undefined reference to 'free_irq'
drivers/power/max8903_charger.c:359: undefined reference to 'free_irq'

This commit fixes the issue by making the driver depend on
GENERIC_HARDIRQS feature.

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Anton Vorontsov <cbouatmailru@gmail.com>