staging: spectra: fix build error
blk_queue_ordered() has been deprecated and replaced with
blk_queue_flush() by Tejun. However, use of blk_queue_ordered()
in spectra nand driver has not been converted yet and thus results
in the following build error.

drivers/staging/spectra/ffsport.c: In function SBD_setup_device:
drivers/staging/spectra/ffsport.c:659: error: implicit declaration of function blk_queue_ordered
drivers/staging/spectra/ffsport.c:659: error: QUEUE_ORDERED_DRAIN_FLUSH undeclared (first use in this function)
drivers/staging/spectra/ffsport.c:659: error: (Each undeclared identifier is reported only once
drivers/staging/spectra/ffsport.c:659: error: for each function it appears in.)

Signed-off-by: Yong Wang <yong.y.wang@intel.com>
Cc: Tejun Heo <tj@kernel.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>