ARM: mach-shmobile: ag5evm needs CONFIG_I2C
ag5evm implements a backlight control, using an I2C controller, therefore
it needs CONFIG_I2C to fix this make failure

arch/arm/mach-shmobile/built-in.o: In function `lcd_on':
pfc-sh73a0.c:(.text+0x2334): undefined reference to `i2c_get_adapter'
pfc-sh73a0.c:(.text+0x2370): undefined reference to `i2c_transfer'

(ignore pfc-sh73a0.c) and to build successfully.

Signed-off-by: Guennadi Liakhovetski <g.liakhovetski@gmx.de>
Signed-off-by: Paul Mundt <lethal@linux-sh.org>