staging: comedi: usbduxsigma: add missing spaces reported by checkpatch.pl
checkpatch.pl reports:

ERROR: space required after that ',' (ctx:VxV)
+               dev_dbg(dev->class_dev,"CRC error in ISO IN stream\n");
                                      ^

ERROR: spaces required around that '=' (ctx:VxW)
+       struct usbduxsigma_private *devpriv= dev->private;
                                           ^
Add the missing spaces to avoid the error.

Signed-off-by: H Hartley Sweeten <hsweeten@visionengravers.com>
Cc: Ian Abbott <abbotti@mev.co.uk>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>