xtensa: add missing include asm/uaccess.h to checksum.h
This fixes the following build errors seen in the linux-next:

arch/xtensa/include/asm/checksum.h:247:2: error: implicit declaration of
	function 'access_ok' [-Werror=implicit-function-declaration]
arch/xtensa/include/asm/checksum.h:247:16: error: 'VERIFY_WRITE' undeclared
	(first use in this function)

Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>
Signed-off-by: Chris Zankel <chris@zankel.net>