SFI / ACPI: Fix warnings reported during builds with W=1
The following warnings can be seen in W=1 builds, because the original
sfi_acpi.[ch] header inclusions are incorrect:

include/linux/sfi_acpi.h:72:2: error: implicit declaration of function 'acpi_table_parse' [-Werror=implicit-function-declaration]
drivers/sfi/sfi_acpi.c:154:5: warning: no previous prototype for 'sfi_acpi_table_parse' [-Wmissing-prototypes]

Fix linux/sfi_acpi.h and modify drivers/sfi/sfi_acpi.c accordingly.

Reported-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: Lv Zheng <lv.zheng@intel.com>
[rjw: Subject and changelog]
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>