cpufreq: kirkwood: Select CPU_FREQ_TABLE option
We need to select CPU_FREQ_TABLE in order to build without
this kind of errors:

drivers/built-in.o: In function `kirkwood_cpufreq_cpu_exit':
/home/zeta/linux-devel/marvell-legacy/drivers/cpufreq/kirkwood-cpufreq.c:145:
undefined reference to `cpufreq_frequency_table_put_attr'

Signed-off-by: Ezequiel Garcia <ezequiel.garcia@free-electrons.com>
Acked-by: Jason Cooper <jason@lakedaemon.net>
Signed-off-by: Viresh Kumar <viresh.kumar@linaro.org>