staging: lustre: ptlrpc: clean up whitespace around braces
Fix the following types of checkpatch errors to comply with coding
style:

ERROR: space required after that close brace '}'
ERROR: space required before the open brace '{'

Also change "if (x == 0)" into "if (!x)" on one line, to avoid
introducing new checkpatch issues.

Signed-off-by: Kristina Martsenko <kristina.martsenko@gmail.com>
Reviewed-by: Sarah Sharp <sarah.a.sharp@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>