staging: dgap: fix missing header inclusion
Include slab.h to fix the following compilation error:

  drivers/staging/dgap/dgap_fep5.c: In function ‘dgap_do_config_load’:
  drivers/staging/dgap/dgap_fep5.c:78:2: error: implicit declaration of function ‘kzalloc’ [-Werror=implicit-function-declaration]

Signed-off-by: Vincent Stehlé <vincent.stehle@laposte.net>
Cc: Lidza Louina <lidza.louina@gmail.com>
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Cc: Scott H Kilau <Scott_Kilau@digi.com>
Cc: Eng.Linux@digi.com
Cc: trivial@kernel.org
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>