staging: rtl8187se: Fix whitespaces in ieee80211/dot11d.h
This patch fixes whitespaces as the codingStyle of the kernel recommends.

Thus, this patch fixes these errors found by checkpatch.pl in r8180.h

ERROR: space required after that close brace '}'
ERROR: space required after that ',' (ctx:VxV)
ERROR: spaces required around that '==' (ctx:VxV)
ERROR: spaces required around that '=' (ctx:VxV)
ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Ana Rey <anarey@gmail.com>
Acked-by: Bob Copeland <me@bobcopeland.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>