pm2301_charger: Remove __dev* annotations
The removal of __devinit and friends seems to have overlapped with the
addition of the pm2301_charger driver. Currently the driver fails to build
with the following errors:

	drivers/power/pm2301_charger.c:843:22: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'pm2xxx_wall_charger_probe'
	drivers/power/pm2301_charger.c:1013:22: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'pm2xxx_wall_charger_remove'
	drivers/power/pm2301_charger.c:1049:11: error: 'pm2xxx_wall_charger_probe' undeclared here (not in a function)
	drivers/power/pm2301_charger.c:1050:2: error: implicit declaration of function '__devexit_p'
	drivers/power/pm2301_charger.c:1050:24: error: 'pm2xxx_wall_charger_remove' undeclared here (not in a function)

This patch removes the __dev* annotations, which fixes the build errors.

Cc: Lee Jones <lee.jones@linaro.org>
Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Linus Walleij <linus.walleij@linaro.org>
Signed-off-by: Anton Vorontsov <anton@enomsg.org>