[IA64] Resolve name space collision for cache_show()
We have a local static function named rather generically
"cache_show()". Changes in progress in the slab code want
to use this same name globally - so they are adding their
declaration to <linux/slab.h> which then causes the compiler
to choke with:

arch/ia64/kernel/topology.c:278: error: conflicting types for 'cache_show'

Fix by adding an "ia64_" prefix to our local function.

Signed-off-by: Tony Luck <tony.luck@intel.com>