staging: bcm: Cleanup switch statement
Fixes checkpatch.pl warnings and errors:

ERROR: switch and case should be at the same indent
+	switch (status) {
[...]
+	    case STATUS_SUCCESS:
[...]
+		case -ENOENT :
[...]
+		case -EINPROGRESS:
[...]
+		case -EPIPE:
[...]
+	    case -ECONNRESET: //URB got unlinked.
+	    case -ESHUTDOWN:		// hardware gone. this is the serious problem.
[...]
+	    case -ENODEV : //Device got removed
+		case -EINVAL : //Some thing very bad happened with the URB. No description is available.
[...]
+	    default:

ERROR: that open brace { should be on the previous line
+		if ( urb->actual_length )
+		{

ERROR: space prohibited after that open parenthesis '('
+		if ( urb->actual_length )

ERROR: space prohibited before that close parenthesis ')'
+		if ( urb->actual_length )

ERROR: that open brace { should be on the previous line
+			if(psIntfAdapter->ulInterruptData[1] & 0xFF)
+			{

ERROR: space required before the open parenthesis '('
+			if(psIntfAdapter->ulInterruptData[1] & 0xFF)

WARNING: line over 80 characters
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL, "Got USIM interrupt");

ERROR: space required after that ',' (ctx:VxV)
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL, "Got USIM interrupt");
 				                       ^
ERROR: that open brace { should be on the previous line
+			if(psIntfAdapter->ulInterruptData[1] & 0xFF00)
+			{

ERROR: space required before the open parenthesis '('
+			if(psIntfAdapter->ulInterruptData[1] & 0xFF00)

WARNING: line over 80 characters
+					(psIntfAdapter->ulInterruptData[1] & 0xFF00) >> 8);

WARNING: space prohibited between function name and open parenthesis '('
+				atomic_set (&Adapter->uiMBupdate, TRUE);

WARNING: line over 80 characters
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL, "TX mailbox contains %d",

ERROR: space required after that ',' (ctx:VxV)
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL, "TX mailbox contains %d",
 				                       ^
+					atomic_read(&Adapter->CurrNumFreeTxDesc));

ERROR: that open brace { should be on the previous line
+			if(psIntfAdapter->ulInterruptData[1] >> 16)
+			{

ERROR: space required before the open parenthesis '('
+			if(psIntfAdapter->ulInterruptData[1] >> 16)

ERROR: spaces required around that '=' (ctx:VxE)
+				Adapter->CurrNumRecvDescs=
 				                         ^

WARNING: line over 80 characters
+					(psIntfAdapter->ulInterruptData[1]  >> 16);
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"RX mailbox contains %d",

ERROR: space required after that ',' (ctx:VxV)
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"RX mailbox contains %d",
 				                       ^

ERROR: space required after that ',' (ctx:VxV)
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"RX mailbox contains %d",
 				                                                               ^

ERROR: that open brace { should be on the previous line
+			if(Adapter->fw_download_done &&
+				!Adapter->downloadDDR &&
+				atomic_read(&Adapter->CurrNumFreeTxDesc))
+			{

ERROR: space required before the open parenthesis '('
+			if(Adapter->fw_download_done &&

ERROR: spaces required around that '+=' (ctx:WxV)
+				psIntfAdapter->psAdapter->downloadDDR +=1;
 				                                      ^

ERROR: that open brace { should be on the previous line
+			if(false == Adapter->waiting_to_fw_download_done)
+			{

ERROR: space required before the open parenthesis '('
+			if(false == Adapter->waiting_to_fw_download_done)

ERROR: that open brace { should be on the previous line
+			if(!atomic_read(&Adapter->TxPktAvail))
+			{

ERROR: space required before the open parenthesis '('
+			if(!atomic_read(&Adapter->TxPktAvail))

WARNING: line over 80 characters
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"Firing interrupt in URB");

ERROR: space required after that ',' (ctx:VxV)
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"Firing interrupt in URB");
 			                       ^

ERROR: space required after that ',' (ctx:VxV)
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"Firing interrupt in URB");
 			                                                               ^

ERROR: space prohibited before that ':' (ctx:WxE)
+		case -ENOENT :
 		             ^

WARNING: line over 80 characters
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"URB has got disconnected ....");

ERROR: space required after that ',' (ctx:VxV)
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"URB has got disconnected ....");
 			                       ^

ERROR: space required after that ',' (ctx:VxV)
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"URB has got disconnected ....");
 			                                                               ^

WARNING: space prohibited before semicolon
+			return ;

WARNING: line over 80 characters
+			//This situation may happened when URBunlink is used. for detail check usb_unlink_urb documentation.

ERROR: do not use C99 // comments
+			//This situation may happened when URBunlink is used. for detail check usb_unlink_urb documentation.

WARNING: line over 80 characters
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"Impossibe condition has occurred... something very bad is going on");

ERROR: space required after that ',' (ctx:VxV)
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"Impossibe condition has occurred... something very bad is going on");
 			                       ^

ERROR: space required after that ',' (ctx:VxV)
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"Impossibe condition has occurred... something very bad is going on");
 			                                                               ^

WARNING: space prohibited before semicolon
+			break ;

ERROR: do not use C99 // comments
+			//return;

WARNING: line over 80 characters
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"Interrupt IN endPoint  has got halted/stalled...need to clear this");

ERROR: space required after that ',' (ctx:VxV)
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"Interrupt IN endPoint  has got halted/stalled...need to clear this");
 				                       ^

ERROR: space required after that ',' (ctx:VxV)
+				BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"Interrupt IN endPoint  has got halted/stalled...need to clear this");
 				                                                               ^

WARNING: space prohibited before semicolon
+				Adapter->bEndPointHalted = TRUE ;

WARNING: space prohibited before semicolon
+				urb->status = STATUS_SUCCESS ;

ERROR: do not use C99 // comments
+	    case -ECONNRESET: //URB got unlinked.

WARNING: line over 80 characters
+	    case -ESHUTDOWN:		// hardware gone. this is the serious problem.

ERROR: do not use C99 // comments
+	    case -ESHUTDOWN:		// hardware gone. this is the serious problem.

WARNING: line over 80 characters
+	    						//Occurs only when something happens with the host controller device

ERROR: code indent should use tabs where possible
+^I    ^I^I^I^I^I^I//Occurs only when something happens with the host controller device$

WARNING: please, no space before tabs
+^I    ^I^I^I^I^I^I//Occurs only when something happens with the host controller device$

ERROR: do not use C99 // comments
+	    						//Occurs only when something happens with the host controller device

ERROR: do not use C99 // comments
+	    case -ENODEV : //Device got removed

ERROR: space prohibited before that ':' (ctx:WxW)
+	    case -ENODEV : //Device got removed
 	                 ^

WARNING: line over 80 characters
+		case -EINVAL : //Some thing very bad happened with the URB. No description is available.

ERROR: do not use C99 // comments
+		case -EINVAL : //Some thing very bad happened with the URB. No description is available.

ERROR: space prohibited before that ':' (ctx:WxW)
+		case -EINVAL : //Some thing very bad happened with the URB. No description is available.
 		             ^

WARNING: line over 80 characters
+	    	BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"interrupt urb error %d", status);

ERROR: code indent should use tabs where possible
+^I    ^IBCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"interrupt urb error %d", status);$

WARNING: please, no space before tabs
+^I    ^IBCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"interrupt urb error %d", status);$

ERROR: space required after that ',' (ctx:VxV)
+	    	BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"interrupt urb error %d", status);
 	    	                       ^

ERROR: space required after that ',' (ctx:VxV)
+	    	BCM_DEBUG_PRINT(Adapter,DBG_TYPE_OTHERS, INTF_INIT, DBG_LVL_ALL,"interrupt urb error %d", status);
 	    	                                                               ^

WARNING: space prohibited before semicolon
+			urb->status = STATUS_SUCCESS ;

WARNING: space prohibited before semicolon
+			break ;

ERROR: do not use C99 // comments
+			//return;

ERROR: spaces required around that ':' (ctx:VxE)
+	    default:
 	           ^

WARNING: line over 80 characters
+			//This is required to check what is the defaults conditions when it occurs..

ERROR: do not use C99 // comments
+			//This is required to check what is the defaults conditions when it occurs..

WARNING: line over 80 characters
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_TX, NEXT_SEND, DBG_LVL_ALL,"GOT DEFAULT INTERRUPT URB STATUS :%d..Please Analyze it...", status);

ERROR: space required after that ',' (ctx:VxV)
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_TX, NEXT_SEND, DBG_LVL_ALL,"GOT DEFAULT INTERRUPT URB STATUS :%d..Please Analyze it...", status);
 			                       ^

ERROR: space required after that ',' (ctx:VxV)
+			BCM_DEBUG_PRINT(Adapter,DBG_TYPE_TX, NEXT_SEND, DBG_LVL_ALL,"GOT DEFAULT INTERRUPT URB STATUS :%d..Please Analyze it...", status);
 			                                                           ^
Signed-off-by: Jade Bilkey <herself@thefumon.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>