Staging rtl8192e: Fixing checkpatch error in rtllib_debug.h
In rtllib_debug.h we fixed the following checkpatch error:
	ERROR: Macros with complex values should be enclosed in parenthesis

We fixed this with a do {} while (0), because otherwise the compiler complained.

Signed-off-by: Andreas Frembs <andreas.frembs@studium.uni-erlangen.de>
Signed-off-by: Matthias Schoepe <matthias.schoepe@studium.uni-erlangen.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>