staging: solo6010 depends on I2C
This driver uses i2c interfaces, so it should depend on I2C
(unless someone wants to break it into pieces or make it more
config-dependent).

drivers/staging/solo6x10/solo6010-i2c.c:47: error: implicit declaration of function 'i2c_transfer'
drivers/staging/solo6x10/solo6010-i2c.c:299: error: implicit declaration of function 'i2c_add_adapter'
drivers/staging/solo6x10/solo6010-i2c.c:310: error: implicit declaration of function 'i2c_del_adapter'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Ben Collins <bcollins@bluecherry.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>