MIPS: SNI: pcimt: Guard sni_controller with CONFIG_PCI
Fixes the following build problem:

arch/mips/sni/pcimt.c:188:30: error: 'sni_controller'
defined but not used [-Werror=unused-variable]

Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>
Acked-by: Steven J. Hill <Steven.Hill@imgtec.com>
Cc: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/5547/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>