Staging: wlags49_h2: fix spaces, macros and comments coding style issue in debug.h
This is a patch to the debug.h file that fixed up a TAB and spaces
Errors found by the checkpatch.pl tools, like
	spaces required around that '&' (ctx:VxV)
and
	ERROR: Invalid UTF-8, patch and commit message should be encoded in UTF-8
and
	do not use C99 // comments
and
	Macros with complex values should be enclosed in parenthesis

Signed-off-by: Ruslan Pisarev <ruslan@rpisarev.org.ua>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>