staging:rtl8723au: core: Added missing space reported by checkpatch.
This is a patch to the rtw_cmd.c file that fixes following
Error.

ERROR: spaces required around that '>' (ctx:WxV)

Signed-off-by: Sanjeev Sharma <Sanjeev_Sharma@mentor.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>