mmc: dw_mmc: add missing MFD_SYSCON dependency for SOCFPGA
Added missing MFD_SYSCON dependency for SOCFPGA in order to fix
the following link error.

drivers/mmc/host/dw_mmc-socfpga.c:49: undefined reference to `syscon_regmap_lookup_by_compatible'

Signed-off-by: Jingoo Han <jg1.han@samsung.com>
Acked-by: Jaehoon Chung <jh80.chung@samsung.com>
Acked-by: Seungwon Jeon <tgih.jun@samsung.com>
Signed-off-by: Chris Ball <cjb@laptop.org>